export default {
  /**
   * This value is arbitrary and used when making GQL queries to AppSync.
   * It is used to fetch "all" records in cases where pagination is unnecessary.
   */
  arbitraryQueryLimit: 1000,
  app: {
    name: 'SRI',
    companyName: 'SRI Pte. Ltd.',
    absoluteUrl: 'https://sri-autoweb.vercel.app',
    nakedDomain: 'sri.com.sg',
  },
  socialProfileLinks: {
    facebook: 'https://facebook.com/sriexperience',
    linkedin: 'https://www.linkedin.com/company/singapore-realtors-inc-sri/',
    youtube: 'https://www.youtube.com/channel/UCoLyLwHukBF2k-muqqDnzpQ',
    instagram: 'https://www.instagram.com',
    twitter: 'https://www.twitter.com',
  },
  meta: {
    title: 'SRI',
  },
  // aws object here should mirror aws-exports.js generated by amplify
  aws: {
    aws_project_region: process.env.aws_project_region,
    aws_appsync_graphqlEndpoint: process.env.aws_appsync_graphqlEndpoint,
    aws_appsync_region: process.env.aws_appsync_region,
    aws_appsync_authenticationType: process.env.aws_appsync_authenticationType,
    aws_appsync_apiKey: process.env.aws_appsync_apiKey,
    aws_cloud_logic_custom: [
      {
        name: 'mailgen',
        endpoint: process.env.aws_cloud_logic_custom_mailgen_endpoint,
        region: 'ap-southeast-1',
      },
      {
        name: 'pdfgen',
        endpoint: process.env.aws_cloud_logic_custom_pdfgen_endpoint,
        region: 'ap-southeast-1',
      },
      {
        name: 'fetchApi',
        endpoint: process.env.aws_cloud_logic_custom_fetch_api_endpoint,
        region: 'ap-southeast-1',
      },
      {
        name: 'mail',
        endpoint: process.env.aws_cloud_logic_custom_mail_endpoint,
        region: 'ap-southeast-1',
      },
    ],
    aws_cognito_identity_pool_id: process.env.aws_cognito_identity_pool_id,
    aws_cognito_region: process.env.aws_cognito_region,
    aws_user_pools_id: process.env.aws_user_pools_id,
    aws_user_pools_web_client_id: process.env.aws_user_pools_web_client_id,
    oauth: {},
    aws_user_files_s3_bucket: process.env.aws_user_files_s3_bucket,
    aws_user_files_s3_bucket_region: process.env.aws_user_files_s3_bucket_region,
    aws_mobile_analytics_app_id: process.env.aws_mobile_analytics_app_id,
    aws_mobile_analytics_app_region: process.env.aws_mobile_analytics_app_region,
  },
  mail: {
    aws_pinpoint_access_key_id: process.env.aws_pinpoint_access_key_id,
    aws_pinpoint_secret_access_key: process.env.aws_pinpoint_secret_access_key,
    defaultFrom: 'SRI <noreply@sri.com>',
  },
  analytics: {
    ga: {
      trackingId: '',
    },
    fp: {
      pixelId: '',
    },
  },
  seo: {
    title: '',
    description: '',
    image: '',
    url: '',
  },
  google: {
    maps: {
      key: process.env.google_map_key,
    },
  },
  autoweb: {
    autowebID: process.env.AUTOWEB_ID,
  },
}
